
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish to NPM
        uses: AwesomeHamster/actions-publish@master
        with:
          token: ${{ secrets.NPM_TOKEN }}
          # 以下为可选参数（有默认值，可按需覆盖）
          node-version: '20'
          test: yarn test
          install-peer: koishi
