
on: push

jobs:
  npm-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 安装koishi
      run: npm init koishi@latest
    
    - run: ls
    - run: cat package.json

    - name: 引入源码
      run: npm koishi-scripts clone DMB-codegang/koishi-plugin-codegang-qd

    - name: 项目打包
      run: npm yakumo build codegang-qd
