
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: 上传到action以供下载
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./lib
