
on: push

jobs:
  npm-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 安装koishi
      run: npm install koishi
    
    - run: ls

    - name: 引入源码
      run: npm run clone DMB-codegang/koishi-plugin-codegang-qd

    - name: 项目打包
      run: npm run build codegang-qd
