
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 导入源码
        uses: actions/checkout@v4
      - name: 安装Node
        uses: actions/setup-node@v4
      - name: 安装依赖
        run: yarn
      - name: 编译
        run: yarn build
      - name: 上传到GitHub
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./lib
      - name: 发布到npm
        if: success()
        run: |
          yarn publish --non-interactive  # 使用 yarn 来发布到 npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
